language: minimal

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10

before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi;
  - if [ $TRAVIS_OS_NAME = "osx" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi;
  - bash ./miniconda.sh -b -p ./miniconda3 && source ./miniconda3/bin/activate;
  - conda init bash && source $HOME/.bashrc;
  - conda update -q --yes conda;
  - conda config --add channels conda-forge;
  - export GOPOATH=`pwd`/go.pkgs
  - conda install -q --yes sed openssl go;
  - (cd seqkit && go get go get ./...);

script:
    - ./tests/test.sh
